# -*- coding: utf-8 -*-
import streamlit as st
import os
from datetime import datetime
from pathlib import Path
import sys
import io
import logging
import threading
import time
import re
from contextlib import redirect_stdout, redirect_stderr
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Add the src directory to the path
sys.path.insert(0, str(Path(__file__).parent / "src"))

from dev_aem_crew_sys.crew import DevAemCrewSys

# Set up logging to capture crew logs
log_file = "crew_execution.log"

# Create a custom handler that writes to file and can be monitored
class StreamlitLogHandler(logging.Handler):
    def __init__(self, log_list):
        super().__init__()
        self.log_list = log_list

    def emit(self, record):
        log_entry = self.format(record)
        self.log_list.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": record.levelname.lower(),
            "message": log_entry
        })

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_file, mode='w'),
        logging.StreamHandler(sys.stdout)
    ]
)

# ========================================
# ANALYSIS DOCUMENTATION FUNCTIONS
# ========================================

def create_analysis_documentation(json_path, output_path):
    """
    Create a markdown documentation file from the design analysis JSON.
    This is for user documentation only, not used by agents.
    """
    try:
        import json
        from datetime import datetime

        # Read the JSON file
        with open(json_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Strip markdown code fences if present (CrewAI sometimes wraps JSON in ```json blocks)
        content = content.strip()
        if content.startswith('```json'):
            content = content[7:]  # Remove ```json
        elif content.startswith('```'):
            content = content[3:]  # Remove ```
        if content.endswith('```'):
            content = content[:-3]  # Remove closing ```
        content = content.strip()

        # Parse JSON
        analysis = json.loads(content)

        # Create markdown content
        md_content = f"""# Design Analysis Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

**Source File:** {st.session_state.uploaded_image_path if st.session_state.uploaded_image_path else 'N/A'}

---

## 📦 Component Overview

| Property | Value |
|----------|-------|
| **Name** | `{analysis.get('component', {}).get('name', 'N/A')}` |
| **Type** | `{analysis.get('component', {}).get('type', 'N/A')}` |
| **Width** | `{analysis.get('component', {}).get('width', 'N/A')}` |
| **Height** | `{analysis.get('component', {}).get('height', 'N/A')}` |

---

## 🎨 Color Palette

"""

        # Add colors
        colors = analysis.get('colors', {})
        if colors:
            for color_name, color_value in colors.items():
                md_content += f"- **{color_name.title()}:** `{color_value}` <span style='display:inline-block;width:20px;height:20px;background:{color_value};border:1px solid #ccc;vertical-align:middle;'></span>\n"
        else:
            md_content += "*No colors specified*\n"

        md_content += "\n---\n\n## 📐 Layout Structure\n\n"

        # Add layout
        layout = analysis.get('layout', {})
        if layout:
            md_content += "```css\n"
            for key, value in layout.items():
                md_content += f"{key}: {value};\n"
            md_content += "```\n"
        else:
            md_content += "*No layout specified*\n"

        md_content += "\n---\n\n## 🧩 Elements\n\n"

        # Add elements
        elements = analysis.get('elements', [])
        if elements:
            for idx, element in enumerate(elements, 1):
                element_type = element.get('type', 'unknown')
                md_content += f"### Element {idx}: {element_type.title()}\n\n"

                # Create table for element properties
                md_content += "| Property | Value |\n|----------|-------|\n"
                for key, value in element.items():
                    if key != 'type':
                        # Handle nested objects/arrays
                        if isinstance(value, (dict, list)):
                            value_str = json.dumps(value, indent=2)
                            md_content += f"| **{key}** | `{value_str}` |\n"
                        else:
                            md_content += f"| **{key}** | `{value}` |\n"

                md_content += "\n"
        else:
            md_content += "*No elements specified*\n"

        md_content += """
---

## 📝 Notes

This analysis was automatically generated by the **Visual Strategist** agent.

The JSON specification can be found at: `output-visual_strategist/design_analysis.json`

---

*Generated by AEMplify - Powered by CrewAI & Claude AI*
"""

        # Write markdown file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md_content)

        print(f"✅ Successfully wrote markdown documentation to: {output_path}")
        return True

    except json.JSONDecodeError as e:
        print(f"❌ JSON Parse Error: {str(e)}")
        print(f"   Problem parsing JSON at line {e.lineno}, column {e.colno}")
        print(f"   Content preview: {content[:200] if 'content' in locals() else 'N/A'}")
        return False
    except Exception as e:
        print(f"❌ Error creating analysis documentation: {str(e)}")
        import traceback
        traceback.print_exc()
        return False

# ========================================
# AEM PROJECT AUTO-DETECTION FUNCTIONS
# ========================================

def detect_aem_project_settings(project_path):
    """
    Auto-detect AEM project configuration from the project structure.
    Returns a dict with: aem_app_id, aem_namespace, aem_component_group
    """
    if not project_path or not os.path.exists(project_path):
        return None

    result = {
        'aem_app_id': '',
        'aem_namespace': '',
        'aem_component_group': ''
    }

    try:
        # 1. Detect aem_app_id from ui.apps/src/main/content/jcr_root/apps/ folder structure
        apps_path = os.path.join(project_path, 'ui.apps', 'src', 'main', 'content', 'jcr_root', 'apps')
        if os.path.exists(apps_path):
            # Get first non-system folder (exclude 'acs-commons', 'cq', 'dam', 'wcm', etc.)
            system_folders = {'acs-commons', 'cq', 'dam', 'wcm', 'sling', 'granite', 'libs'}
            app_folders = [f for f in os.listdir(apps_path)
                          if os.path.isdir(os.path.join(apps_path, f))
                          and f not in system_folders
                          and not f.startswith('.')]
            if app_folders:
                result['aem_app_id'] = app_folders[0]

        # 2. Detect aem_namespace from pom.xml or archetype.properties
        # Try archetype.properties first (most reliable)
        archetype_file = os.path.join(project_path, 'archetype.properties')
        if os.path.exists(archetype_file):
            with open(archetype_file, 'r') as f:
                content = f.read()
                # Look for package=com.example.project
                match = re.search(r'package\s*=\s*([a-zA-Z0-9_.]+)', content)
                if match:
                    result['aem_namespace'] = match.group(1).split('.')[-1]  # Get last part

        # Fallback: Try to detect from Java package structure
        if not result['aem_namespace']:
            core_path = os.path.join(project_path, 'core', 'src', 'main', 'java')
            if os.path.exists(core_path):
                # Walk through the first few levels to find the package
                for root, dirs, files in os.walk(core_path):
                    java_files = [f for f in files if f.endswith('.java')]
                    if java_files:
                        # Extract package from first Java file
                        with open(os.path.join(root, java_files[0]), 'r') as f:
                            first_line = f.readline()
                            if 'package' in first_line:
                                match = re.search(r'package\s+([a-zA-Z0-9_.]+)', first_line)
                                if match:
                                    package = match.group(1)
                                    # Extract the main namespace (e.g., com.mohhwebsites.core.models -> mohhwebsites)
                                    parts = package.split('.')
                                    if len(parts) >= 2:
                                        result['aem_namespace'] = parts[1]  # Usually the second part
                        break

        # 3. Detect aem_component_group from existing component .content.xml
        if result['aem_app_id']:
            components_path = os.path.join(apps_path, result['aem_app_id'], 'components')
            if os.path.exists(components_path):
                # Find first component with .content.xml
                for root, dirs, files in os.walk(components_path):
                    if '.content.xml' in files:
                        xml_file = os.path.join(root, '.content.xml')
                        try:
                            with open(xml_file, 'r') as f:
                                content = f.read()
                                # Look for componentGroup="..."
                                match = re.search(r'componentGroup\s*=\s*["\']([^"\']+)["\']', content)
                                if match:
                                    result['aem_component_group'] = match.group(1)
                                    break
                        except:
                            pass
                    if result['aem_component_group']:
                        break

        # Set default component group if not found
        if not result['aem_component_group'] and result['aem_app_id']:
            result['aem_component_group'] = f"{result['aem_app_id'].title()} - Content"

        return result

    except Exception as e:
        st.error(f"Error detecting AEM project settings: {str(e)}")
        return None

# Page configuration
st.set_page_config(
    page_title="AEMplify - Design to AEM Component Converter",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for beautiful UI
st.markdown("""
<style>
    /* Main theme colors */
    :root {
        --primary-color: #4B3C99;
        --secondary-color: #E85C23;
        --success-color: #28a745;
        --error-color: #dc3545;
    }

    /* Header styling */
    .main-header {
        background: linear-gradient(135deg, #4B3C99 0%, #E85C23 100%);
        padding: 2rem;
        border-radius: 10px;
        margin-bottom: 2rem;
        text-align: center;
        color: white;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }

    .main-header h1 {
        font-size: 3rem;
        font-weight: 800;
        margin: 0;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
    }

    .main-header p {
        font-size: 1.2rem;
        margin-top: 0.5rem;
        opacity: 0.95;
    }

    /* Header with integrated button layout */
    .main-header-left {
        background: linear-gradient(135deg, #4B3C99 0%, #E85C23 100%);
        padding: 2rem;
        border-radius: 10px 0 0 10px;
        margin-bottom: 2rem;
        text-align: center;
        color: white;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        height: 100%;
    }

    .main-header-left h1 {
        font-size: 3rem;
        font-weight: 800;
        margin: 0;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
    }

    .main-header-left p {
        font-size: 1.2rem;
        margin-top: 0.5rem;
        opacity: 0.95;
    }

    /* Header button container */
    .header-button-container {
        background: linear-gradient(135deg, #4B3C99 0%, #E85C23 100%);
        padding: 2rem 1.5rem;
        border-radius: 0 10px 10px 0;
        margin-bottom: 2rem;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100%;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }

    /* Adjust column spacing for header */
    div[data-testid="column"]:has(.header-button-container) {
        padding-left: 0 !important;
    }

    div[data-testid="column"]:has(.main-header-left) {
        padding-right: 0 !important;
    }

    /* Log container */
    .log-container {
        background: #1e1e1e;
        color: #00ff00;
        padding: 1.5rem;
        border-radius: 10px;
        font-family: 'Courier New', monospace;
        font-size: 0.9rem;
        max-height: 600px;
        overflow-y: auto;
        margin-top: 1rem;
        box-shadow: inset 0 2px 4px rgba(0,0,0,0.3);
    }

    .log-entry {
        margin: 0.3rem 0;
        line-height: 1.5;
    }

    .log-info { color: #00d4ff; }
    .log-success { color: #00ff00; }
    .log-warning { color: #ffa500; }
    .log-error { color: #ff4444; }

    /* Agent badges */
    .agent-badge {
        display: inline-block;
        padding: 0.5rem 1rem;
        border-radius: 20px;
        margin: 0.5rem;
        font-weight: 600;
        color: white;
    }

    .agent-designer { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
    .agent-developer { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
    .agent-aem { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }

    /* Status indicators */
    .status-ready { color: #28a745; }
    .status-running { color: #ffa500; animation: pulse 2s infinite; }
    .status-complete { color: #4B3C99; }

    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.6; }
    }

    /* Button styling */
    .stButton>button {
        background: linear-gradient(135deg, #4B3C99 0%, #E85C23 100%);
        color: white;
        font-weight: 600;
        padding: 0.75rem 2rem;
        border-radius: 8px;
        border: none;
        font-size: 1.1rem;
        transition: transform 0.2s;
    }

    .stButton>button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(75, 60, 153, 0.4);
    }

    /* Upload box */
    .uploadedFile {
        border: 2px dashed #4B3C99;
        border-radius: 10px;
        padding: 1rem;
    }

    /* Data Migration button specific styling */
    div[data-testid="column"]:has(button[data-testid*="data_migration"]) {
        display: flex;
        align-items: flex-start;
        justify-content: flex-end;
    }

    /* Make Data Migration button stand out - white/light style for header */
    .header-button-container button {
        background: white !important;
        color: #4B3C99 !important;
        border: 2px solid white !important;
        box-shadow: 0 3px 10px rgba(0, 0, 0, 0.2) !important;
        font-weight: 700 !important;
        font-size: 1rem !important;
        padding: 0.75rem 1.5rem !important;
        transition: all 0.3s ease !important;
    }

    .header-button-container button:hover {
        background: rgba(255, 255, 255, 0.9) !important;
        transform: translateY(-2px) !important;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3) !important;
    }

    /* Cool drag-and-drop styling */
    [data-testid="stFileUploader"] {
        border: 2px dashed #4B3C99 !important;
        border-radius: 10px !important;
        padding: 1.5rem !important;
        background: linear-gradient(135deg, rgba(75, 60, 153, 0.05) 0%, rgba(232, 92, 35, 0.05) 100%) !important;
        transition: all 0.3s ease !important;
    }

    [data-testid="stFileUploader"]:hover {
        border-color: #E85C23 !important;
        background: linear-gradient(135deg, rgba(75, 60, 153, 0.1) 0%, rgba(232, 92, 35, 0.1) 100%) !important;
        transform: scale(1.02);
        box-shadow: 0 4px 12px rgba(75, 60, 153, 0.2);
    }

    [data-testid="stFileUploader"] section {
        border: none !important;
    }

    [data-testid="stFileUploader"] button {
        background: linear-gradient(135deg, #4B3C99 0%, #E85C23 100%) !important;
        color: white !important;
        border: none !important;
        border-radius: 6px !important;
        padding: 0.5rem 1rem !important;
        font-weight: 600 !important;
    }

    /* Quick select radio buttons styling */
    [data-testid="stRadio"] {
        background: #f8f9fa;
        padding: 1rem;
        border-radius: 8px;
        border: 1px solid #dee2e6;
    }

    [data-testid="stRadio"] label {
        font-weight: 500;
    }

    /* Simplified Professional Timeline */
    .timeline-section {
        margin: 1.5rem 0;
        padding: 1rem 1.5rem;
        background: #ffffff;
        border-radius: 8px;
        border: 1px solid #e9ecef;
    }

    .timeline-horizontal {
        display: flex;
        justify-content: space-around;
        align-items: flex-start;
        position: relative;
        padding: 1rem 0.5rem;
        gap: 1.5rem;
    }

    /* Simple connecting line */
    .timeline-horizontal::before {
        content: '';
        position: absolute;
        top: 30px;
        left: 30%;
        right: 30%;
        height: 2px;
        background: #dee2e6;
        z-index: 0;
    }

    .agent-column {
        flex: 1;
        text-align: center;
        position: relative;
        z-index: 1;
        max-width: 180px;
    }

    /* Clean icon container */
    .agent-icon-container {
        width: 60px;
        height: 60px;
        margin: 0 auto 0.75rem;
        border-radius: 10px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 2rem;
        position: relative;
        background: #f8f9fa;
        border: 2px solid #dee2e6;
        transition: all 0.3s ease;
    }

    .agent-icon-container.pending {
        background: #f8f9fa;
        border-color: #dee2e6;
        opacity: 0.6;
    }

    .agent-icon-container.active {
        background: #fff3cd;
        border-color: #ffc107;
        transform: scale(1.05);
        box-shadow: 0 3px 10px rgba(255, 193, 7, 0.3);
    }

    .agent-icon-container.completed {
        background: #d4edda;
        border-color: #28a745;
    }

    /* Simple status badge */
    .agent-status-badge {
        position: absolute;
        top: -5px;
        right: -5px;
        width: 22px;
        height: 22px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 0.75rem;
        font-weight: bold;
        background: white;
        border: 2px solid white;
        box-shadow: 0 2px 4px rgba(0,0,0,0.15);
    }

    .agent-status-badge.pending {
        background: #6c757d;
        color: white;
    }

    .agent-status-badge.active {
        background: #ffc107;
        color: white;
        animation: pulse-badge 1.5s infinite;
    }

    .agent-status-badge.completed {
        background: #28a745;
        color: white;
    }

    @keyframes pulse-badge {
        0%, 100% { transform: scale(1); }
        50% { transform: scale(1.15); }
    }

    /* Agent name */
    .agent-name-display {
        font-size: 0.9rem;
        font-weight: 600;
        margin-bottom: 0.4rem;
        color: #2c3e50;
    }

    .agent-name-display.pending { color: #6c757d; }
    .agent-name-display.active { color: #e85c23; }
    .agent-name-display.completed { color: #28a745; }

    /* Status text */
    .agent-status-text {
        font-size: 0.65rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        margin-bottom: 0.5rem;
        padding: 0.2rem 0.6rem;
        border-radius: 10px;
        display: inline-block;
    }

    .agent-status-text.pending {
        background: #e9ecef;
        color: #6c757d;
    }

    .agent-status-text.active {
        background: #fff3cd;
        color: #856404;
    }

    .agent-status-text.completed {
        background: #d4edda;
        color: #155724;
    }

    /* Task chips */
    .agent-task-list {
        margin-top: 0.5rem;
        min-height: 30px;
    }

    .task-chip {
        display: inline-block;
        padding: 0.25rem 0.6rem;
        border-radius: 5px;
        font-size: 0.65rem;
        margin: 0.15rem;
        font-weight: 500;
        background: #f8f9fa;
        color: #495057;
        border: 1px solid #dee2e6;
    }

    .task-chip.completed {
        background: #d4edda;
        color: #155724;
        border-color: #c3e6cb;
    }

    .task-chip.active {
        background: #fff3cd;
        color: #856404;
        border-color: #ffc107;
    }

    /* Time display */
    .agent-time-display {
        font-size: 0.65rem;
        color: #6c757d;
        margin-top: 0.5rem;
        padding: 0.3rem;
        background: #f8f9fa;
        border-radius: 5px;
    }

    /* Live status banner */
    .live-status-banner {
        background: #4B3C99;
        color: white;
        padding: 1rem 1.5rem;
        border-radius: 8px;
        margin-bottom: 1.5rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        border: 1px solid rgba(255,255,255,0.1);
    }

    .live-status-left {
        display: flex;
        align-items: center;
        gap: 0.75rem;
    }

    .live-indicator {
        width: 8px;
        height: 8px;
        background: #28a745;
        border-radius: 50%;
        animation: blink 1.5s infinite;
    }

    @keyframes blink {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.3; }
    }

    .live-status-text {
        font-size: 0.75rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 1px;
    }

    .live-status-agent {
        font-size: 1.1rem;
        font-weight: 600;
    }

    .live-status-progress {
        font-size: 0.85rem;
        opacity: 0.9;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.markdown("""
<div class="main-header">
    <h1>⚡ AEMplify</h1>
    <p>Transform UI Designs into AEM Components with AI-Powered Automation</p>
</div>
""", unsafe_allow_html=True)

# Initialize session state
if 'crew_running' not in st.session_state:
    st.session_state.crew_running = False
if 'crew_started' not in st.session_state:
    st.session_state.crew_started = False
if 'logs' not in st.session_state:
    st.session_state.logs = []
if 'uploaded_image_path' not in st.session_state:
    st.session_state.uploaded_image_path = None
if 'log_monitor_thread' not in st.session_state:
    st.session_state.log_monitor_thread = None
if 'last_log_position' not in st.session_state:
    st.session_state.last_log_position = 0
if 'agent_status' not in st.session_state:
    st.session_state.agent_status = {
        'visual_strategist': {'status': 'pending', 'tasks': [], 'start_time': None, 'end_time': None},
        'aem_alchemist': {'status': 'pending', 'tasks': [], 'start_time': None, 'end_time': None}
    }
if 'current_agent' not in st.session_state:
    st.session_state.current_agent = None
if 'task_progress' not in st.session_state:
    st.session_state.task_progress = []

# Initialize session state for AEM settings
if 'aem_project_path' not in st.session_state:
    st.session_state.aem_project_path = ""
if 'aem_app_id' not in st.session_state:
    st.session_state.aem_app_id = ""
if 'aem_namespace' not in st.session_state:
    st.session_state.aem_namespace = ""
if 'aem_component_group' not in st.session_state:
    st.session_state.aem_component_group = ""
if 'aem_settings_detected' not in st.session_state:
    st.session_state.aem_settings_detected = False
if 'selected_agents' not in st.session_state:
    st.session_state.selected_agents = ['visual_strategist', 'aem_alchemist']  # Both by default
if 'show_data_migration' not in st.session_state:
    st.session_state.show_data_migration = False

# Sidebar - Configuration
with st.sidebar:
    # Data Migration button at the top
    if st.button("📊 Data Migration", key="data_migration_btn", use_container_width=True, type="primary"):
        st.session_state.show_data_migration = True

    st.markdown("---")  # Separator line

    st.markdown("### ⚙️ Configuration")

    # Set default output folder (not shown in UI)
    output_folder = "output"

    # ========================================
    # AGENT SELECTION
    # ========================================
    st.markdown("#### 🤖 Agent Selection")

    st.markdown("**Choose which agents to run:**")

    # Agent 1: Visual Strategist
    agent1_selected = st.checkbox(
        "📊 Visual Strategist",
        value='visual_strategist' in st.session_state.selected_agents,
        help="Analyzes design image and creates JSON specification",
        key="agent1_checkbox"
    )

    # Agent 2: AEM Alchemist (depends on Visual Strategist output)
    agent2_selected = st.checkbox(
        "⚡ AEM Alchemist",
        value='aem_alchemist' in st.session_state.selected_agents,
        help="Generates AEM component files from JSON specification",
        key="agent2_checkbox"
    )

    # Update selected agents in session state
    selected_agents = []
    if agent1_selected:
        selected_agents.append('visual_strategist')
    if agent2_selected:
        selected_agents.append('aem_alchemist')

    st.session_state.selected_agents = selected_agents

    # Show warning if AEM Alchemist is selected without Visual Strategist
    if agent2_selected and not agent1_selected:
        # Check if design_analysis.json exists
        if not os.path.exists('output-visual_strategist/design_analysis.json'):
            st.warning("⚠️ **AEM Alchemist requires design_analysis.json**\n\nEither:\n- Select Visual Strategist to generate it, or\n- Ensure output-visual_strategist/design_analysis.json exists from a previous run")
        else:
            st.info("✓ Using existing design_analysis.json from previous run")

    # Show selected workflow
    if selected_agents:
        st.markdown("**Selected Workflow:**")
        workflow_text = " → ".join([
            "📊 Visual Strategist" if 'visual_strategist' in selected_agents else "",
            "⚡ AEM Alchemist" if 'aem_alchemist' in selected_agents else ""
        ]).replace(" →  → ", " → ").strip(" → ")
        st.markdown(f"<div style='background: #e8f4f8; padding: 0.5rem; border-radius: 5px; font-size: 0.9rem;'>{workflow_text}</div>", unsafe_allow_html=True)
    else:
        st.error("❌ Please select at least one agent!")

    st.markdown("---")

    # ========================================
    # AEM SETTINGS
    # ========================================
    st.markdown("#### 🏗️ AEM Settings")

    # Helpful expander with instructions
    with st.expander("💡 How to get your AEM project path"):
        st.markdown("""
        **Quick Guide:**

        1. **Open your AEM project folder** in Finder (Mac) or File Explorer (Windows)
        2. **Copy the full path:**
           - **Mac**: Right-click folder → Hold Option → Click "Copy as Pathname"
           - **Windows**: Click address bar → Copy path
        3. **Paste it below** and click "🔍 Auto-Detect Settings"

        **Example paths:**
        - Mac: `/Users/username/projects/mohh-websites-revamp`
        - Windows: `C:\\Users\\username\\projects\\mohh-websites-revamp`

        **What we'll detect:**
        - ✓ App ID from `ui.apps/.../apps/[app-name]/`
        - ✓ Java namespace from `archetype.properties`
        - ✓ Component group from existing components
        """)

    # AEM Project Path with auto-detect button
    aem_project_path_input = st.text_input(
        "AEM Project Path",
        value=st.session_state.aem_project_path,
        placeholder="Paste your AEM project path here",
        help="Full path to your AEM project root (where pom.xml is located)",
        key="aem_path_input"
    )

    # Auto-detect button
    col1, col2 = st.columns([2, 1])
    with col1:
        auto_detect_button = st.button("🔍 Auto-Detect Settings", key="auto_detect_settings", use_container_width=True)
    with col2:
        clear_button = st.button("🗑️ Clear", key="clear_settings", use_container_width=True)

    # Handle auto-detect button
    if auto_detect_button:
        if aem_project_path_input and os.path.exists(aem_project_path_input):
            with st.spinner("🔍 Scanning AEM project structure..."):
                st.session_state.aem_project_path = aem_project_path_input

                # Auto-detect settings
                detected = detect_aem_project_settings(aem_project_path_input)
                if detected and (detected['aem_app_id'] or detected['aem_namespace']):
                    st.session_state.aem_app_id = detected['aem_app_id']
                    st.session_state.aem_namespace = detected['aem_namespace']
                    st.session_state.aem_component_group = detected['aem_component_group']
                    st.session_state.aem_settings_detected = True
                    st.success(f"✅ Detected: **{detected['aem_app_id']}** | Namespace: **{detected['aem_namespace']}**")
                    st.rerun()
                else:
                    st.warning("⚠️ Could not auto-detect settings. Please verify the path points to an AEM project root folder.")
        elif aem_project_path_input:
            st.error("❌ Path doesn't exist! Please check the path and try again.")
        else:
            st.info("💡 Please paste your AEM project path first.")

    # Handle clear button
    if clear_button:
        st.session_state.aem_project_path = ""
        st.session_state.aem_app_id = ""
        st.session_state.aem_namespace = ""
        st.session_state.aem_component_group = ""
        st.session_state.aem_settings_detected = False
        st.rerun()

    # Update session state if path changed manually (for real-time updates)
    if aem_project_path_input != st.session_state.aem_project_path:
        st.session_state.aem_project_path = aem_project_path_input

    # Show detection status
    if st.session_state.aem_settings_detected:
        st.success("✓ Auto-detected from project structure")

    st.markdown("---")

    # Auto-populated fields (editable)
    aem_app_id = st.text_input(
        "AEM App ID",
        value=st.session_state.aem_app_id,
        placeholder="e.g., mohhwebsites",
        help="Your AEM application ID (auto-detected from ui.apps/...jcr_root/apps/)",
        key="aem_app_id_input"
    )
    st.session_state.aem_app_id = aem_app_id

    aem_namespace = st.text_input(
        "Java Namespace",
        value=st.session_state.aem_namespace,
        placeholder="e.g., mohhwebsites",
        help="Java package namespace (auto-detected from archetype.properties or Java files)",
        key="aem_namespace_input"
    )
    st.session_state.aem_namespace = aem_namespace

    aem_component_group = st.text_input(
        "Component Group",
        value=st.session_state.aem_component_group,
        placeholder="e.g., MOHH Websites - Content",
        help="Component group name in AEM (auto-detected from existing components)",
        key="aem_component_group_input"
    )
    st.session_state.aem_component_group = aem_component_group

    # Use the session state values for the rest of the app
    aem_project_path = st.session_state.aem_project_path

# ========================================
# DATA MIGRATION DIALOG
# ========================================
if st.session_state.show_data_migration:
    # Create a modal-like dialog using st.dialog (Streamlit 1.31+)
    @st.dialog("📊 Data Migration", width="large")
    def data_migration_dialog():
        st.markdown("### Data Migration Tool")
        st.markdown("Migrate website components directly to AEM using the migration script.")

        # Migration Configuration
        st.markdown("#### 🔧 Migration Configuration")

        col1, col2 = st.columns(2)

        with col1:
            # AEM Page Path
            page_path = st.text_input(
                "AEM Page Path",
                value="/content/mohhwebsites/us/hackathon-demo-page",
                help="Target page path in AEM where components will be created",
                key="migration_page_path"
            )

            # AEM Host
            aem_host = st.text_input(
                "AEM Host",
                value="http://localhost:4502",
                help="AEM server URL",
                key="migration_aem_host"
            )

        with col2:
            # Container Path (advanced)
            container_path = st.text_input(
                "Container Path",
                value="/jcr:content/root/container/container",
                help="Container path within the page",
                key="migration_container_path"
            )

        st.markdown("---")

        # JSON File Upload Section - Full Width Drag and Drop
        st.markdown("#### 📁 Upload JSON File")

        # Drag and drop uploader - full width
        uploaded_file = st.file_uploader(
            "Drag and drop your JSON file here or click to browse",
            type=['json'],
            help="Upload a JSON file in AEM component format (demo-components.json, physician_mohh_aem.json, or custom)",
            key="migration_custom_upload"
        )

        # Determine which JSON file to use
        json_file_path = None
        json_file_name = None

        if uploaded_file:
            # Save uploaded file temporarily
            import tempfile
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, encoding='utf-8') as f:
                json_content = uploaded_file.read().decode('utf-8')
                f.write(json_content)
                json_file_path = f.name
                json_file_name = uploaded_file.name
            st.success(f"✅ Ready to migrate: **{uploaded_file.name}**")
        else:
            st.info("📤 Please upload a JSON file to continue (e.g., demo-components.json, physician_mohh_aem.json)")

        st.markdown("---")

        # Action Buttons
        col1, col2, col3 = st.columns(3)

        with col1:
            dry_run = st.button("🧪 Dry Run (Test)", use_container_width=True, help="Test migration without making changes")

        with col2:
            migrate = st.button("🚀 Migrate to AEM", use_container_width=True, type="primary", help="Execute migration")

        with col3:
            close_btn = st.button("❌ Close", use_container_width=True)

        if close_btn:
            st.session_state.show_data_migration = False
            st.rerun()

        # Execute migration
        if (dry_run or migrate) and json_file_path:
            import subprocess

            # Build command
            cmd = [
                "python",
                "hackathon-demo-script/migrate.py",
                "--page", page_path,
                "--json", json_file_path,
                "--host", aem_host,
                "--container", container_path
            ]

            if dry_run:
                cmd.append("--dry-run")

            st.markdown("---")

            with st.spinner("🔄 Running migration..." if not dry_run else "🧪 Running dry run..."):
                try:
                    # Execute command
                    result = subprocess.run(
                        cmd,
                        capture_output=True,
                        text=True,
                        timeout=60
                    )

                    # Show status - simplified
                    if result.returncode == 0:
                        st.success("✅ Migration completed successfully!")
                        if not dry_run:
                            page_url = f"{aem_host}{page_path}.html?wcmmode=disabled"
                            st.markdown(f"**🔗 Access page:** [{page_url}]({page_url})")
                        else:
                            st.info("✓ Dry run completed - No changes were made")
                    else:
                        st.error(f"❌ Migration failed")
                        # Show errors only on failure
                        with st.expander("View Error Details"):
                            if result.stderr:
                                st.code(result.stderr)
                            if result.stdout:
                                st.code(result.stdout)

                except subprocess.TimeoutExpired:
                    st.error("⏱️ Migration timed out after 60 seconds")
                except FileNotFoundError:
                    st.error("❌ Migration script not found. Ensure 'hackathon-demo-script/migrate.py' exists.")
                except Exception as e:
                    st.error(f"❌ Error executing migration: {str(e)}")

        elif (dry_run or migrate) and not json_file_path:
            st.warning("⚠️ Please select or upload a JSON file first!")

    # Show the dialog
    data_migration_dialog()

# Main content
col1, col2 = st.columns([1, 1])

with col1:
    st.markdown("### 🖼️ Upload Design Image")

    # Check if AEM project is configured
    aem_configured = (
        st.session_state.aem_project_path and
        st.session_state.aem_app_id and
        st.session_state.aem_namespace and
        st.session_state.aem_component_group
    )

    if not aem_configured:
        st.warning("⚠️ **Please configure AEM Settings first**")
        st.info("👈 Go to the sidebar and:\n1. Paste your AEM project path\n2. Click '🔍 Auto-Detect Settings'\n3. Then come back here to upload your design")

        # Show disabled file uploader with message
        st.file_uploader(
            "Choose a design mockup or screenshot",
            type=['png', 'jpg', 'jpeg', 'gif', 'webp'],
            help="Upload your UI design image (PNG, JPG, JPEG, GIF, WEBP)",
            disabled=True,
            key="disabled_uploader"
        )
        uploaded_file = None
    else:
        # Show enabled file uploader
        uploaded_file = st.file_uploader(
            "Choose a design mockup or screenshot",
            type=['png', 'jpg', 'jpeg', 'gif', 'webp'],
            help="Upload your UI design image (PNG, JPG, JPEG, GIF, WEBP)",
            key="enabled_uploader"
        )

    if uploaded_file is not None:
        # Save uploaded file as design.png (replace existing)
        filename = "design.png"
        filepath = Path(filename)

        with open(filepath, "wb") as f:
            f.write(uploaded_file.getbuffer())

        st.session_state.uploaded_image_path = str(filepath)

        # Professional compact image preview - thumbnail style
        st.markdown(f"""
        <div style="background: #f8f9fa; padding: 1rem; border-radius: 8px; border: 1px solid #dee2e6; margin-top: 1rem;">
            <div style="display: flex; align-items: center; gap: 1rem;">
                <div style="flex-shrink: 0;">
                    <div style="width: 80px; height: 80px; background: white; border-radius: 6px; border: 2px solid #dee2e6; display: flex; align-items: center; justify-content: center; overflow: hidden;">
                        <span style="font-size: 2rem;">🖼️</span>
                    </div>
                </div>
                <div style="flex: 1;">
                    <div style="font-weight: 600; color: #28a745; margin-bottom: 0.25rem;">✓ Design Uploaded</div>
                    <div style="font-size: 0.9rem; color: #495057;">{uploaded_file.name}</div>
                    <div style="font-size: 0.8rem; color: #6c757d; margin-top: 0.25rem;">{uploaded_file.size / 1024:.1f} KB • {uploaded_file.type}</div>
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)

        # Optional: Show preview in expander for those who want to see it
        with st.expander("🔍 View Full Preview"):
            st.image(uploaded_file, use_column_width=True)

with col2:
    st.markdown("### 🚀 Crew Status")

    # Check if everything is ready
    selected_agents = st.session_state.selected_agents
    can_start = False
    status_message = ""

    if not selected_agents:
        status_message = '❌ Select at least one agent...'
    elif not aem_configured:
        status_message = '⚙️ Configure AEM settings first...'
    elif st.session_state.crew_running:
        status_message = '⏳ Crew is running...'
        can_start = False
    elif 'visual_strategist' in selected_agents:
        # Visual Strategist needs an image
        if st.session_state.uploaded_image_path:
            status_message = '✅ Ready to start'
            can_start = True
        else:
            status_message = '📋 Waiting for design upload...'
    elif 'aem_alchemist' in selected_agents and 'visual_strategist' not in selected_agents:
        # AEM only mode - check if JSON exists
        if os.path.exists('output-visual_strategist/design_analysis.json'):
            status_message = '✅ Ready to start (using existing JSON)'
            can_start = True
        else:
            status_message = '❌ design_analysis.json not found'

    st.markdown(f'<p class="{"status-running" if st.session_state.crew_running else "status-ready" if can_start else ""}">{status_message}</p>', unsafe_allow_html=True)

    # Determine if start button should be enabled
    enable_start = can_start and not st.session_state.crew_running

    # Start button - disabled based on validation
    start_button = st.button(
        "Start AEM Conversion",
        disabled=not enable_start,
        use_container_width=True,
        help="Ready to start!" if enable_start else "Check requirements above"
    )

if start_button and enable_start:
    # Clean output folders before starting
    import shutil
    output_folders = ['output-visual_strategist', 'output-aem_alchemist']
    for folder in output_folders:
        if os.path.exists(folder):
            print(f"🧹 Removing folder: {folder}")
            shutil.rmtree(folder)
        os.makedirs(folder, exist_ok=True)
        print(f"✨ Created fresh folder: {folder}")

    st.session_state.crew_running = True
    st.session_state.crew_started = True  # Mark that crew has been started
    st.session_state.logs = []
    # Reset agent status
    st.session_state.agent_status = {
        'visual_strategist': {'status': 'pending', 'tasks': [], 'start_time': None, 'end_time': None},
        'aem_alchemist': {'status': 'pending', 'tasks': [], 'start_time': None, 'end_time': None}
    }
    print(f"🔄 Reset agent status to PENDING")
    print(f"   Visual Strategist: {st.session_state.agent_status['visual_strategist']['status']}")
    print(f"   AEM Alchemist: {st.session_state.agent_status['aem_alchemist']['status']}")

    st.session_state.current_agent = None
    st.session_state.task_progress = []

    # Add initial log
    st.session_state.logs.append({
        "timestamp": datetime.now().strftime("%H:%M:%S"),
        "level": "info",
        "message": "🧹 Cleaned output folders"
    })
    st.session_state.logs.append({
        "timestamp": datetime.now().strftime("%H:%M:%S"),
        "level": "info",
        "message": "AEMplify starting..."
    })

    st.rerun()

# Function to render horizontal agent timeline
def render_agent_timeline():
    """Render the professional horizontal agent timeline"""

    agent_info = {
        'visual_strategist': {'name': 'Visual Strategist', 'icon': '📊', 'number': '01'},  # Chart icon
        'aem_alchemist': {'name': 'AEM Alchemist', 'icon': '⚡', 'number': '02'}  # Lightning icon
    }

    # Filter to only show selected agents
    selected_agents = st.session_state.get('selected_agents', ['visual_strategist', 'aem_alchemist'])

    # Live status banner (if crew is running)
    if st.session_state.crew_running and st.session_state.current_agent:
        current_agent_info = agent_info.get(st.session_state.current_agent)
        if current_agent_info:  # Only show if agent is in selected list
            current_tasks = st.session_state.agent_status[st.session_state.current_agent]['tasks']
            current_task = current_tasks[-1] if current_tasks else "Initializing..."

            st.markdown(f"""
            <div class="live-status-banner">
                <div class="live-status-left">
                    <div class="live-indicator"></div>
                    <div class="live-status-text">LIVE EXECUTION</div>
                </div>
                <div>
                    <div class="live-status-agent">{current_agent_info['name']}</div>
                    <div class="live-status-progress">{current_task}</div>
                </div>
            </div>
            """, unsafe_allow_html=True)

    # Horizontal timeline
    timeline_html = '<div class="timeline-section">'
    timeline_html += '<div class="timeline-horizontal">'

    # Only loop through selected agents
    for agent_id in selected_agents:
        agent_data = st.session_state.agent_status[agent_id]
        status = agent_data['status']
        tasks = agent_data['tasks']
        info = agent_info[agent_id]

        # Agent column
        timeline_html += '<div class="agent-column">'

        # Icon container with status
        timeline_html += f'<div class="agent-icon-container {status}">'
        timeline_html += f'<span style="font-size: 2rem;">{info["icon"]}</span>'

        # Status badge with number or checkmark
        if status == 'completed':
            badge_content = '✓'  # Checkmark
        elif status == 'active':
            badge_content = info['number']
        else:
            badge_content = info['number']

        timeline_html += f'<div class="agent-status-badge {status}">{badge_content}</div>'
        timeline_html += '</div>'

        # Agent name
        timeline_html += f'<div class="agent-name-display {status}">{info["name"]}</div>'

        # Status text
        if status == 'completed':
            status_text = 'COMPLETED'
        elif status == 'active':
            status_text = 'IN PROGRESS'
        else:
            status_text = 'PENDING'

        timeline_html += f'<div class="agent-status-text {status}">{status_text}</div>'

        # Tasks
        if tasks:
            timeline_html += '<div class="agent-task-list">'
            for task in tasks:
                task_status = 'completed' if status == 'completed' else ('active' if status == 'active' else 'pending')
                timeline_html += f'<span class="task-chip {task_status}">{task}</span>'
            timeline_html += '</div>'
        else:
            timeline_html += '<div class="agent-task-list"></div>'

        # Time info
        if agent_data['start_time']:
            start_str = agent_data['start_time'].strftime("%H:%M:%S")
            if agent_data['end_time']:
                end_str = agent_data['end_time'].strftime("%H:%M:%S")
                duration = (agent_data['end_time'] - agent_data['start_time']).seconds
                timeline_html += f'<div class="agent-time-display">Duration: {duration}s<br>{start_str} → {end_str}</div>'
            else:
                timeline_html += f'<div class="agent-time-display">Started: {start_str}</div>'

        # View Files button - only show if agent completed
        if status == 'completed':
            # Map agent to their output folder
            output_folders = {
                'visual_strategist': 'output-visual_strategist',
                'aem_alchemist': 'output-aem_alchemist'
            }
            folder = output_folders.get(agent_id, '')
            timeline_html += f'''
            <div style="margin-top: 0.75rem;">
                <button onclick="window.viewAgentFiles('{agent_id}', '{folder}')"
                        style="background: #4B3C99; color: white; border: none; padding: 0.4rem 0.8rem;
                               border-radius: 6px; font-size: 0.7rem; cursor: pointer; font-weight: 600;
                               transition: all 0.2s;">
                    📁 View Files
                </button>
            </div>
            '''

        timeline_html += '</div>'  # Close agent-column

    timeline_html += '</div></div>'  # Close timeline-horizontal and timeline-section

    # Add JavaScript for handling file viewing
    timeline_html += '''
    <script>
    window.viewAgentFiles = function(agentId, folder) {
        // Create a custom event that Streamlit can listen to
        const event = new CustomEvent('viewFiles', {
            detail: { agentId: agentId, folder: folder }
        });
        window.dispatchEvent(event);

        // Show alert for now (can be replaced with modal)
        alert('📁 Files location: ' + folder + '\\n\\nCheck the folder in your project directory to view the created files.');
    }
    </script>
    '''

    st.markdown(timeline_html, unsafe_allow_html=True)

    # File viewer expanders for completed agents
    # Only show when agent status is actually completed
    json_file = 'output-visual_strategist/design_analysis.json'
    md_file = 'output-visual_strategist/design_analysis.md'

    if st.session_state.agent_status['visual_strategist']['status'] == 'completed':
        with st.expander("📄 Visual Strategist Output - Design Analysis", expanded=True):

            # Show tabs for MD and JSON
            tab1, tab2 = st.tabs(["📖 Documentation (MD)", "📋 Raw JSON"])

            with tab1:
                try:
                    if os.path.exists(md_file):
                        with open(md_file, 'r', encoding='utf-8') as f:
                            md_content = f.read()
                            st.markdown(md_content)

                        # Download button for markdown
                        col1, col2 = st.columns([1, 1])
                        with col1:
                            st.download_button(
                                label="⬇️ Download MD",
                                data=md_content,
                                file_name="design_analysis.md",
                                mime="text/markdown",
                                use_container_width=True
                            )
                    else:
                        st.info("📄 Markdown documentation will appear here when analysis is complete...")
                except Exception as e:
                    st.error(f"Error reading markdown: {str(e)}")

            with tab2:
                try:
                    if os.path.exists(json_file):
                        with open(json_file, 'r', encoding='utf-8') as f:
                            json_content = f.read()

                        # Strip markdown code fences for display (CrewAI wraps output in ```json)
                        display_content = json_content.strip()
                        if display_content.startswith('```json'):
                            display_content = display_content[7:]
                        elif display_content.startswith('```'):
                            display_content = display_content[3:]
                        if display_content.endswith('```'):
                            display_content = display_content[:-3]
                        display_content = display_content.strip()

                        st.code(display_content, language='json', line_numbers=True)

                        # Download button for cleaned JSON
                        col1, col2 = st.columns([1, 1])
                        with col1:
                            st.download_button(
                                label="⬇️ Download JSON",
                                data=display_content,
                                file_name="design_analysis.json",
                                mime="application/json",
                                use_container_width=True
                            )
                    else:
                        st.info("📋 JSON specification will appear here when analysis is complete...")
                except Exception as e:
                    st.error(f"Error reading JSON: {str(e)}")

    # Removed ui_architect file viewer section as agent is no longer used

    if st.session_state.agent_status['aem_alchemist']['status'] == 'completed':
        with st.expander("📄 AEM Alchemist Output - AEM Files"):
            st.info("AEM files created in your project directory. Check the logs for file paths.")

# ========================================
# TIMELINE SECTION (Shows above logs) - Dynamic placeholder
# ========================================
st.markdown("---")
timeline_placeholder = st.empty()

# Render timeline if crew has started
if st.session_state.crew_started:
    with timeline_placeholder.container():
        render_agent_timeline()

    # Debug status display (collapsible)
    with st.expander("🔍 Debug: Agent Status", expanded=False):
        for agent_id, agent_data in st.session_state.agent_status.items():
            agent_names = {
                'visual_strategist': '📊 Visual Strategist',
                'aem_alchemist': '⚡ AEM Alchemist'
            }
            st.markdown(f"**{agent_names.get(agent_id, agent_id)}**")
            col1, col2, col3 = st.columns(3)
            with col1:
                status_emoji = {
                    'pending': '⏳',
                    'active': '🔄',
                    'completed': '✅'
                }
                st.write(f"Status: {status_emoji.get(agent_data['status'], '❓')} {agent_data['status'].upper()}")
            with col2:
                st.write(f"Tasks: {len(agent_data['tasks'])}")
            with col3:
                if agent_data['start_time']:
                    st.write(f"Started: {agent_data['start_time'].strftime('%H:%M:%S')}")
            if agent_data['tasks']:
                st.write(f"Task list: {', '.join(agent_data['tasks'])}")
            st.markdown("---")

# ========================================
# LOGS SECTION
# ========================================
st.markdown("---")
st.markdown("### 📋 Execution Logs")

# Log container
log_placeholder = st.empty()

# Function to strip ANSI color codes
def strip_ansi_codes(text):
    """Remove ANSI color/formatting codes from text"""
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)

# Function to detect and update agent/task status from logs
def update_agent_status_from_log(line):
    """Detect agent and task changes from log lines and update status - EXPERT MODE"""

    # Define agent and task mapping based on actual crew configuration
    agent_task_mapping = {
        'visual_strategist': ['Design Analysis'],
        'aem_alchemist': ['AEM Component Definition', 'HTL Generation', 'Sling Model', 'Dialog', 'SCSS', 'JavaScript', 'Verification']
    }

    agent_order = ['visual_strategist', 'aem_alchemist']

    # ========== AGENT DETECTION ==========
    # Multiple patterns to catch agent activation in CrewAI logs

    # Pattern 1: "Working Agent: <role>" - Most reliable
    if "Working Agent:" in line:
        if "Visual Strategist" in line:
            activate_agent('visual_strategist')
        # Removed ui_architect activation
        elif "AEM Alchemist" in line:
            activate_agent('aem_alchemist')

    # Pattern 2: "# Agent: <role>" - Markdown header in logs
    elif "# Agent:" in line:
        if "Visual Strategist" in line:
            activate_agent('visual_strategist')
        # Removed ui_architect activation
        elif "AEM Alchemist" in line:
            activate_agent('aem_alchemist')

    # Pattern 3: Agent name in brackets [Agent: role]
    elif "[Agent:" in line or "Agent:" in line:
        if "Visual Strategist" in line:
            activate_agent('visual_strategist')
        # Removed ui_architect activation
        elif "AEM Alchemist" in line:
            activate_agent('aem_alchemist')

    # Pattern 4: "Entering new" chain with agent context
    elif "Entering new" in line and "chain" in line:
        # This indicates an agent is starting work
        # Need to infer from previous context or next lines
        pass

    # Pattern 5: Task-based agent detection (fallback)
    elif "## Task:" in line or "Task Description:" in line or "Starting Task:" in line:
        # Detect which agent should be active based on task name
        if "design_analysis" in line.lower():
            activate_agent('visual_strategist')
        # Removed ui_architect task-based detection
        elif "aem_component" in line.lower() or "aem_build" in line.lower() or "aem_testing" in line.lower():
            activate_agent('aem_alchemist')

    # Pattern 6: Output file detection (very reliable)
    elif "output-visual_strategist" in line:
        activate_agent('visual_strategist')
    # Removed ui_architect output detection
    elif "output-aem_alchemist" in line:
        activate_agent('aem_alchemist')

    # ========== TASK DETECTION - ACTUAL OUTPUTS ==========
    current = st.session_state.current_agent

    # Detect actual component/file creation for each agent
    if current:
        task_detected = None

        # Visual Strategist outputs
        if current == 'visual_strategist':
            if "design_analysis" in line.lower() or "saved to output-visual_strategist" in line.lower():
                task_detected = "Design Analysis"

        # Removed ui_architect task detection

        # AEM Alchemist outputs
        elif current == 'aem_alchemist':
            # Detect component selection
            if "aem_component_selection" in line.lower() or "component to convert" in line.lower():
                if "Component Selection" not in st.session_state.agent_status[current]['tasks']:
                    task_detected = "Selection"

            # Detect AEM files created
            elif ".content.xml" in line or "sling model" in line.lower() or "htl template" in line.lower():
                if "AEM Component" not in st.session_state.agent_status[current]['tasks']:
                    task_detected = "AEM Component"

            # Detect Maven build
            elif "mvn clean install" in line.lower() or "build success" in line.lower():
                if "Build" not in st.session_state.agent_status[current]['tasks']:
                    task_detected = "Build"

            # Detect testing
            elif "testing" in line.lower() or "aem_testing_report" in line.lower():
                if "Testing" not in st.session_state.agent_status[current]['tasks']:
                    task_detected = "Testing"

        # Add task if detected and not already present
        if task_detected and task_detected not in st.session_state.agent_status[current]['tasks']:
            st.session_state.agent_status[current]['tasks'].append(task_detected)

    # ========== COMPLETION DETECTION ==========
    # Detect when tasks/agents finish

    # Pattern 1: Task completion indicators
    if any(pattern in line for pattern in ["Finished chain", "Final Answer:", "Task output saved"]):
        # A task just completed
        if current:
            # Add completion marker to current task
            pass

    # Pattern 2: Agent switching indicates previous agent completed
    # This is already handled in activate_agent() function

    # Pattern 3: Specific task completion patterns
    if ("design_analysis" in line and "saved" in line.lower()) or \
       ("output-visual_strategist/design_analysis.json" in line) or \
       ("design_analysis_task" in line and "output saved" in line.lower()):
        # Visual Strategist completed
        mark_agent_complete('visual_strategist')

        # Note: Markdown file is now created directly by vision_tool.py
        # Just log that analysis is complete
        md_path = 'output-visual_strategist/design_analysis.md'
        if os.path.exists(md_path):
            print(f"✅ Markdown documentation created by Vision Tool: {md_path}")
            st.session_state.logs.append({
                "timestamp": datetime.now().strftime("%H:%M:%S"),
                "level": "info",
                "message": "📄 Design analysis markdown created"
            })
        else:
            print(f"⚠️ Markdown file not found, Vision Tool may not have completed yet")
    # Removed ui_architect completion detection
    elif ("07_verification_report.txt" in line and "saved" in line.lower()) or \
         ("output-aem_alchemist/07_verification_report.txt" in line) or \
         ("aem_component_verification_task" in line and "output saved" in line.lower()):
        # AEM Alchemist completed all tasks
        print(f"🔍 Detected AEM verification report completion")
        mark_agent_complete('aem_alchemist')
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "info",
            "message": "✅ AEM Alchemist completed all component generation tasks"
        })

def mark_agent_complete(agent_id):
    """Helper function to mark an agent as completed"""
    agent_names = {
        'visual_strategist': 'Visual Strategist',
        'aem_alchemist': 'AEM Alchemist'
    }

    if agent_id in st.session_state.agent_status:
        current_status = st.session_state.agent_status[agent_id]['status']
        print(f"[STATUS] Attempting to mark {agent_names.get(agent_id, agent_id)} as completed (current: {current_status})")

        if st.session_state.agent_status[agent_id]['status'] == 'active':
            st.session_state.agent_status[agent_id]['status'] = 'completed'
            if not st.session_state.agent_status[agent_id]['end_time']:
                st.session_state.agent_status[agent_id]['end_time'] = datetime.now()
            print(f"[STATUS] ✅ {agent_names.get(agent_id, agent_id)} marked as COMPLETED")
        elif st.session_state.agent_status[agent_id]['status'] == 'pending':
            # Allow marking as completed even if not yet active (for single-agent runs)
            st.session_state.agent_status[agent_id]['status'] = 'completed'
            if not st.session_state.agent_status[agent_id]['start_time']:
                st.session_state.agent_status[agent_id]['start_time'] = datetime.now()
            if not st.session_state.agent_status[agent_id]['end_time']:
                st.session_state.agent_status[agent_id]['end_time'] = datetime.now()
            print(f"[STATUS] ✅ {agent_names.get(agent_id, agent_id)} marked as COMPLETED (was pending)")
        else:
            print(f"[STATUS] ⚠️ Agent already in '{current_status}' state, skipping")

def activate_agent(agent_id):
    """Helper function to activate an agent and update status"""
    if agent_id not in st.session_state.agent_status:
        return

    # Skip if already completed
    if st.session_state.agent_status[agent_id]['status'] == 'completed':
        return

    # Get list of selected agents
    selected_agents = st.session_state.get('selected_agents', ['visual_strategist', 'aem_alchemist'])

    agent_order = ['visual_strategist', 'aem_alchemist']
    agent_names = {
        'visual_strategist': 'Visual Strategist',
        'aem_alchemist': 'AEM Alchemist'
    }

    # DO NOT auto-mark previous agents as completed
    # Each agent should be marked complete only when its task actually finishes
    # This was causing premature completion when next agent activates

    # Activate current agent
    if st.session_state.agent_status[agent_id]['status'] != 'completed':
        st.session_state.agent_status[agent_id]['status'] = 'active'
        if not st.session_state.agent_status[agent_id]['start_time']:
            st.session_state.agent_status[agent_id]['start_time'] = datetime.now()
        st.session_state.current_agent = agent_id
        # Log the activation
        print(f"[STATUS] {agent_names[agent_id]} activated")

# Function to filter and clean log lines for professional display
def is_relevant_log(line):
    """Determine if a log line should be displayed to user"""

    # Skip empty lines
    if not line:
        return False

    # Skip repetitive CrewAI internal messages
    skip_patterns = [
        # "Working Agent:",  # NOW KEPT - we use this for status tracking
        # "Starting Task:",  # NOW KEPT - we use this for status tracking
        "[DEBUG]",  # Debug level logs
        "Entering new CrewAgentExecutor chain",  # Internal framework details
        "# Agent:",  # Markdown headers that don't add value
        "## Task:",  # Markdown headers that don't add value
        "Thought: Do I need to use a tool?",  # Repetitive thinking patterns
        "Action Input:",  # Tool input details (too verbose)
        "Observation:",  # Tool observation prefix (redundant)
    ]

    for pattern in skip_patterns:
        if pattern in line:
            return False

    # Keep important log types
    keep_patterns = [
        "[Agent:",  # Agent actions
        "[Tool:",  # Tool usage
        "✓",  # Success indicators
        "✗",  # Failure indicators
        "ERROR",  # Errors
        "Error",  # Errors
        "WARNING",  # Warnings
        "Created",  # File/folder creation
        "Saved",  # File saves
        "Executing",  # Command execution
        "Analyzing",  # Analysis steps
        "Converting",  # Conversion steps
        "Building",  # Build steps
        "Testing",  # Test steps
        "Final Answer:",  # Agent conclusions
    ]

    for pattern in keep_patterns:
        if pattern in line:
            return True

    # Keep lines that look like actual content (not metadata)
    # Skip lines that are just decorative (borders, separators)
    if line.strip() in ["", "─", "│", "┌", "┐", "└", "┘", "═", "║", "╔", "╗", "╚", "╝"]:
        return False

    if all(c in "─│┌┐└┘═║╔╗╚╝-_=*#" for c in line.strip()):
        return False

    # Keep lines that have substantial content
    if len(line.strip()) > 20:
        return True

    return False

# Function to read new logs from file
def read_new_logs():
    """Read new logs from file since last position"""
    if not os.path.exists(log_file):
        return []

    new_logs = []
    try:
        with open(log_file, 'r', encoding='utf-8') as f:
            f.seek(st.session_state.last_log_position)
            new_lines = f.readlines()
            st.session_state.last_log_position = f.tell()

            for line in new_lines:
                # Strip ANSI codes first
                line = strip_ansi_codes(line).strip()

                # Update agent status from this log line
                update_agent_status_from_log(line)

                # Filter out irrelevant logs
                if not is_relevant_log(line):
                    continue

                if line:
                    # Parse log level from line
                    level = "info"
                    if "ERROR" in line or "Error" in line or "✗" in line:
                        level = "error"
                    elif "WARNING" in line or "Warning" in line:
                        level = "warning"
                    elif "SUCCESS" in line or "success" in line or "✓" in line or "Final Answer:" in line:
                        level = "success"

                    new_logs.append({
                        "timestamp": datetime.now().strftime("%H:%M:%S"),
                        "level": level,
                        "message": line
                    })
    except Exception as e:
        pass

    return new_logs

# Function to update log display
def update_log_display():
    """Update the log display in UI"""
    log_html = '<div class="log-container">'
    for log in st.session_state.logs:
        level_class = f"log-{log['level']}"
        log_html += f'<div class="log-entry {level_class}">[{log["timestamp"]}] {log["message"]}</div>'
    log_html += '</div>'
    log_placeholder.markdown(log_html, unsafe_allow_html=True)

# Run crew if started
if st.session_state.crew_running:
    try:
        # Add initial logs
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "info",
            "message": f"Design image: {st.session_state.uploaded_image_path}"
        })
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "info",
            "message": f"Output folder: {output_folder}"
        })
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "info",
            "message": "Initializing crew agents..."
        })

        # Update logs display
        update_log_display()

        # Create crew instance
        crew = DevAemCrewSys()

        # Prepare inputs
        inputs = {
            'design_path': st.session_state.uploaded_image_path,
            'output_folder': output_folder,
            'aem_project_path': aem_project_path,
            'aem_app_id': aem_app_id,
            'aem_namespace': aem_namespace,
            'aem_component_group': aem_component_group,
            'selected_component': 'navbar',  # Default to navbar, will be updated by agent
            'component_name': 'navbar'  # Default to navbar, will be updated by agent
        }

        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "success",
            "message": "Crew initialized successfully"
        })
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "info",
            "message": "Starting crew execution... (This may take a few minutes)"
        })

        # Update logs
        update_log_display()

        # Clear log file before starting
        with open(log_file, 'w') as f:
            f.write("")
        st.session_state.last_log_position = 0

        # Capture selected agents BEFORE starting thread (can't access session_state in thread)
        selected_agents_copy = st.session_state.selected_agents.copy()

        # Function to run crew in background thread
        crew_result = {"result": None, "error": None, "completed": False}

        def run_crew():
            try:
                # Capture stdout and stderr to log file
                class LogCapture:
                    def __init__(self, file_handle, terminal):
                        self.file_handle = file_handle
                        self.terminal = terminal

                    def write(self, message):
                        # Write to both file and terminal
                        self.file_handle.write(message)
                        self.file_handle.flush()
                        if self.terminal:
                            self.terminal.write(message)

                    def flush(self):
                        self.file_handle.flush()
                        if self.terminal:
                            self.terminal.flush()

                # Redirect stdout and stderr to capture all output
                with open(log_file, 'a', encoding='utf-8') as log_f:
                    old_stdout = sys.stdout
                    old_stderr = sys.stderr

                    log_capture_stdout = LogCapture(log_f, old_stdout)
                    log_capture_stderr = LogCapture(log_f, old_stderr)

                    try:
                        sys.stdout = log_capture_stdout
                        sys.stderr = log_capture_stderr

                        # Run the crew based on selected agents (use copied value, not session_state)
                        selected = selected_agents_copy

                        if 'visual_strategist' in selected and 'aem_alchemist' in selected:
                            # Both agents - run full workflow
                            crew_result["result"] = crew.crew().kickoff(inputs=inputs)
                        elif 'visual_strategist' in selected and 'aem_alchemist' not in selected:
                            # Only Visual Strategist - just run design analysis
                            from crewai import Crew, Process
                            visual_crew = Crew(
                                agents=[crew.visual_strategist()],
                                tasks=[crew.design_analysis_task()],
                                process=Process.sequential,
                                verbose=True
                            )
                            crew_result["result"] = visual_crew.kickoff(inputs=inputs)
                        elif 'aem_alchemist' in selected and 'visual_strategist' not in selected:
                            # Only AEM Alchemist - use aem_only_crew (requires existing JSON)
                            crew_result["result"] = crew.aem_only_crew().kickoff(inputs=inputs)
                        else:
                            # No agents selected - shouldn't happen due to validation
                            raise ValueError("No agents selected!")
                    finally:
                        sys.stdout = old_stdout
                        sys.stderr = old_stderr

                crew_result["completed"] = True
            except Exception as e:
                crew_result["error"] = str(e)
                crew_result["completed"] = True

        # Start crew in background thread
        crew_thread = threading.Thread(target=run_crew, daemon=True)
        crew_thread.start()

        # Monitor logs while crew is running
        progress_bar = st.progress(0)
        status_text = st.empty()

        log_check_interval = 0.5  # Check for new logs every 0.5 seconds
        max_wait_time = 600  # Maximum 10 minutes
        elapsed_time = 0

        while not crew_result["completed"] and elapsed_time < max_wait_time:
            # Read new logs
            new_logs = read_new_logs()
            if new_logs:
                st.session_state.logs.extend(new_logs)
                update_log_display()

                # Re-render timeline to show updated agent status
                with timeline_placeholder.container():
                    render_agent_timeline()

            # Update progress
            progress = min(elapsed_time / max_wait_time, 0.99)
            progress_bar.progress(progress)

            # Show current agent in status
            current_agent_name = "Starting..."
            if st.session_state.current_agent:
                agent_names_map = {
                    'visual_strategist': 'Visual Strategist',
                    'aem_alchemist': 'AEM Alchemist'
                }
                current_agent_name = agent_names_map.get(st.session_state.current_agent, "Working...")

            status_text.text(f"🤖 {current_agent_name} - {int(elapsed_time)}s elapsed")

            time.sleep(log_check_interval)
            elapsed_time += log_check_interval

        # Wait for thread to complete
        crew_thread.join(timeout=5)

        # Final log read
        new_logs = read_new_logs()
        if new_logs:
            st.session_state.logs.extend(new_logs)

        progress_bar.progress(1.0)
        status_text.empty()

        # Check for errors
        if crew_result["error"]:
            raise Exception(crew_result["error"])

        result = crew_result["result"]

        # Success
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "success",
            "message": "✓ Crew execution completed successfully!"
        })
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "info",
            "message": f"Result: {str(result)[:200]}..."
        })
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "success",
            "message": "✓ Process finished - Check output folder for generated files"
        })

        # Update final logs
        update_log_display()

        # Markdown is created automatically by Vision Tool
        # Agent completion is tracked via log detection
        print(f"✅ Process completed")

        st.success("✅ Conversion completed successfully!")

    except Exception as e:
        st.session_state.logs.append({
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "level": "error",
            "message": f"❌ Error: {str(e)}"
        })
        st.error(f"Error: {str(e)}")

        # Update error logs
        update_log_display()

    finally:
        st.session_state.crew_running = False
        st.rerun()

# Display logs if not running (running logs are handled above)
if not st.session_state.crew_running:
    if st.session_state.logs:
        update_log_display()
    else:
        log_placeholder.info("Logs will appear here when you start the conversion...")

# Footer
st.markdown("---")
st.markdown("""
<div style="text-align: center; color: #666; padding: 2rem;">
    <p><strong>AEMplify</strong> - Powered by CrewAI & Claude AI</p>
    <p>Design Analysis → AEM Component Generation → Production Ready</p>
</div>
""", unsafe_allow_html=True)
